name = "Humanity Modpack"
author = "copygirl, Human"
version = "0.2.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48235b3238fdd9510f8251ac66d9cee1cb37746e9152b21c5dcc95799a412179"

[versions]
fabric = "0.12.8"
minecraft = "1.18"
