name = "Humanity Modpack"
author = "copygirl, Human"
version = "0.2.2"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "710036d92d4c0a1f5c4ebf0c878467df2e151372ad153832c7d52e0bb36f35db"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18"]
