name = "Humanity Modpack"
author = "copygirl, Human"
version = "0.2.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97429da66df1c86a01f4014357033db55499e193858891ab7ca10c37cbac6a21"

[versions]
fabric = "0.12.8"
minecraft = "1.18"
