name = "Humanity Modpack"
author = "copygirl, Human"
version = "0.2.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96d3f5573fcb162796498715951fe6250d9286ac64054305dfc45c1dfff239ed"

[versions]
fabric = "0.12.9"
minecraft = "1.18"
