name = "Humanity Modpack"
author = "copygirl, Human"
version = "0.2.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13cb8cd105e54c02a96025f82f609748c95965a5b39394334c726082345dd5e6"

[versions]
fabric = "0.12.8"
minecraft = "1.18"
