name = "Humanity Modpack"
author = "copygirl, Human"
version = "0.2.2"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a428912a6870ac33b3bf36bc7d58b13bc63e8020dd5a9955de61f26343e83a91"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18"]
