name = "Humanity Modpack"
author = "copygirl, Human"
version = "0.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a6e5e407f480ba37771e337fa608c3a2b0cc3c27c446f28f7aa4bccab710f80"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"

[options]
acceptable-game-versions = ["1.17"]
