name = "Humanity Modpack"
author = "copygirl, Human"
version = "0.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16ef9afa167135d8f1bec1caedeb9862201d89862754a1facab9ee29c94092ec"

[versions]
fabric = "0.12.5"
minecraft = "1.17.1"
