name = "Humanity Modpack"
author = "copygirl, Human"
version = "0.2.2"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ce632f4558923d4855e8c02c4e75462ea3b011c0f6eef10a128df9d0f9a1451"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18"]
