name = "Adorn"
filename = "Adorn-2.3.1+1.17.1-fabric.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/E6FUtRJh/versions/2.3.1-fabric/Adorn-2.3.1+1.17.1-fabric.jar"
hash-format = "sha512"
hash = "5048ee2e8f6d428df9a738f4fd8d8789dff92380647f2f3edae8de3eb4768d5d93e9c0c9a84c16e9cb014ecf407c3928a5641dfd28d72d84622325f170497a09"

[update]
[update.modrinth]
mod-id = "E6FUtRJh"
version = "bciIHcBm"
