name = "Alternate Current"
filename = "alternate-current-mc1.17-1.1.0.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/r0v8vy1s/versions/mc1.17-1.1.0/alternate-current-mc1.17-1.1.0.jar"
hash-format = "sha512"
hash = "d6aa15fb0581e94d053cca07004f9ade688670bb024761293c62e103577c8fca9be1f7130d40d20960fa1ffb41c005b001420a66ed5d2dd45bc0805c77adefbd"

[update]
[update.modrinth]
mod-id = "r0v8vy1s"
version = "LynxUXOP"
