name = "AppleSkin"
filename = "appleskin-fabric-mc1.18-2.2.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/EsAfCjCV/versions/fabric-mc1.18-2.2.0/appleskin-fabric-mc1.18-2.2.0.jar"
hash-format = "sha512"
hash = "1983bd2560cc36accf150fda8ec9d289e3f48b5e2de157711f657ce9f625ffa07a2bd6b9989c96a6d37e6354fbcf50c9a73211f8f9bafb57296cd39b72e4cb01"

[update]
[update.modrinth]
mod-id = "EsAfCjCV"
version = "c3j4Q3qi"
