name = "BCLib"
filename = "bclib-0.5.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/30/bclib-0.5.5.jar"
hash-format = "murmur2"
hash = "3482379432"

[update]
[update.curseforge]
file-id = 3542030
project-id = 495191
release-channel = "beta"
