name = "Bedspreads (Fabric)"
filename = "bedspreads-fabric-1.4.0-1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3347/431/bedspreads-fabric-1.4.0-1.17.jar"
hash-format = "murmur2"
hash = "578532665"

[update]
[update.curseforge]
file-id = 3347431
project-id = 400477
release-channel = "beta"
