name = "BetterEnd"
filename = "better-end-0.12.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3541/615/better-end-0.12.5.jar"
hash-format = "murmur2"
hash = "3392863934"

[update]
[update.curseforge]
file-id = 3541615
project-id = 413596
release-channel = "beta"
