name = "Better Enchanted Books"
filename = "better-enchanted-books-1.17-1.2.12.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/yjpXhps7/versions/1.2.12/better-enchanted-books-1.17-1.2.12.jar"
hash-format = "sha512"
hash = "ad3c90f3fadb088e31390959ae6cadf70cbc5c9f8ab637dbacc96549752397ce2d6bc38f0a2b2ecd420d348b383aa4b14c5121c730a2a03a34746b32a95ba773"

[update]
[update.modrinth]
mod-id = "yjpXhps7"
version = "LfinCOf1"
