name = "Blur (Fabric)"
filename = "blur-2.4.0.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/NK39zBp2/versions/2.4.0/blur-2.4.0.jar"
hash-format = "sha512"
hash = "a3770e13ff027b7765edbf6717998ee6c737bfd0e3a24680cc2631ad09602cca8fc87e3799a61c7d833d96fe7b33705ab4d5fc6f1ccd693348a722bad28fefe4"

[update]
[update.modrinth]
mod-id = "NK39zBp2"
version = "fqP5zVjW"

[option]
description = "Adds a blur effect to all GUI backgrounds"
optional = true
default = false
