name = "Blur (Fabric)"
filename = "blur-2.4.1.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/NK39zBp2/versions/2.4.1/blur-2.4.1.jar"
hash-format = "sha512"
hash = "3c15159239d5a18e1e66aa5a10a024ee500dfb98da9e884a7d89430367ec15f402d5db29404c39cb7974a766e313243d031bab377be4125e39500bf17fc52923"

[update]
[update.modrinth]
mod-id = "NK39zBp2"
version = "xetUzR7z"

[option]
description = "Adds a blur effect to all GUI backgrounds"
optional = true
default = false
