name = "Better Recipe Book"
filename = "better-recipe-book-1.5.4-1.18.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/vWIaVOTE/versions/1.5.4/better-recipe-book-1.5.4-1.18.jar"
hash-format = "sha512"
hash = "514f54b2e87add224db587ef7e96719bd340e41f53f97e97a075bedab5c042b99f6d4cd8bd5dcc3285c1d93fb3ff4bbee3df3eb72dbbee80fa67e7d25f9934a3"

[update]
[update.modrinth]
mod-id = "vWIaVOTE"
version = "4mpuejW0"
