name = "Cammie's Combat Tweaks"
filename = "combattweaks-1.6.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/HtvWBTYK/versions/1.6/combattweaks-1.6.jar"
hash-format = "sha512"
hash = "4e1965e4bca25659dc4a52545ae2764f6b81bd94de7809f2f7d8d1beada3838f369dfd1f18452cad95af39b4d7f95c3e32b05dcf36e1141769f23c93b3d17f35"

[update]
[update.modrinth]
mod-id = "HtvWBTYK"
version = "xPgqSvoP"
