name = "Chat Heads"
filename = "chat_heads-0.5.1-fabric-1.18.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3543/108/chat_heads-0.5.1-fabric-1.18.jar"
hash-format = "murmur2"
hash = "1146531605"

[update]
[update.curseforge]
file-id = 3543108
project-id = 407206
release-channel = "beta"
