name = "Chat Heads"
filename = "chat_heads-0.5.1-fabric-1.17.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3523/338/chat_heads-0.5.1-fabric-1.17.1.jar"
hash-format = "murmur2"
hash = "1397275704"

[update]
[update.curseforge]
file-id = 3523338
project-id = 407206
release-channel = "beta"
