name = "Chat Heads"
filename = "chat_heads-0.6.0-fabric-1.18.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3570/678/chat_heads-0.6.0-fabric-1.18.1.jar"
hash-format = "murmur2"
hash = "2957109700"

[update]
[update.curseforge]
file-id = 3570678
project-id = 407206
release-channel = "beta"
