name = "ChickensShed"
filename = "chickensshed-1.17.1-1.0.0-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3470/899/chickensshed-1.17.1-1.0.0-fabric.jar"
hash-format = "murmur2"
hash = "69535851"

[update]
[update.curseforge]
file-id = 3470899
project-id = 282684
release-channel = "beta"
