name = "ChickensShed"
filename = "chickensshed-1.18.1-1.3-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3561/793/chickensshed-1.18.1-1.3-fabric.jar"
hash-format = "murmur2"
hash = "1108227323"

[update]
[update.curseforge]
file-id = 3561793
project-id = 282684
release-channel = "beta"
