name = "Detail Armor Bar"
filename = "DetailArmorBar-2.6.1+1.17.1-fabric.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/hAt6ty93/versions/2.6.1/DetailArmorBar-2.6.1+1.17.1-fabric.jar"
hash-format = "sha512"
hash = "1df0303f2b740977d5d536a3ebdb640f655aa991d887363c3bc84b86b1832f76a693b2bdff25ac9efcc0005ff433cd030253a8753f2b60cc4021df7f017ce0d9"

[update]
[update.modrinth]
mod-id = "hAt6ty93"
version = "8gFWsg7v"

[option]
description = "More detail about armor in your armor bar"
optional = true
default = true
