name = "Double Jump Mod [Fabric]"
filename = "doublejump-1.0.1+mc1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3380/681/doublejump-1.0.1+mc1.17.jar"
hash-format = "murmur2"
hash = "1035153895"

[update]
[update.curseforge]
file-id = 3380681
project-id = 401683
release-channel = "beta"
