name = "Ducts"
filename = "ducts-1.1.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3382/43/ducts-1.1.4.jar"
hash-format = "murmur2"
hash = "1778714914"

[update]
[update.curseforge]
file-id = 3382043
project-id = 400219
release-channel = "beta"
