name = "EasyAutoCrafting"
filename = "easy-auto-crafting-1.1+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3544/196/easy-auto-crafting-1.1+1.18.jar"
hash-format = "murmur2"
hash = "535153508"

[update]
[update.curseforge]
file-id = 3544196
project-id = 462134
release-channel = "beta"
