name = "Fabric API"
filename = "fabric-api-0.43.1+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3537/0/fabric-api-0.43.1+1.17.jar"
hash-format = "murmur2"
hash = "1718743756"

[update]
[update.curseforge]
file-id = 3537000
project-id = 306612
release-channel = "beta"
