name = "Fabrication"
filename = "fabrication-1.17-2.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3545/934/fabrication-1.17-2.2.0.jar"
hash-format = "murmur2"
hash = "2667026404"

[update]
[update.curseforge]
file-id = 3545934
project-id = 414445
release-channel = "beta"
