name = "Fabric API"
filename = "fabric-api-0.44.0+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3546/670/fabric-api-0.44.0+1.17.jar"
hash-format = "murmur2"
hash = "2975150040"

[update]
[update.curseforge]
file-id = 3546670
project-id = 306612
release-channel = "beta"
