name = "Falling Leaves"
filename = "fallingleaves-1.7.4+1.17.1.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/WhbRG4iK/versions/1.7.4/fallingleaves-1.7.4+1.17.1.jar"
hash-format = "sha512"
hash = "684642148f3191589571ef0522ba74b1dbf339701b7e87fc4c37443a16022e34cbd68b6d9b7d72f73e46f29a758a11e8f5be657534800390388dad5dfa39d6d2"

[update]
[update.modrinth]
mod-id = "WhbRG4iK"
version = "mqyNUioD"

[option]
description = "Adds a neat little particle effect to leaf blocks"
optional = true
default = true
