name = "Farmer's Delight [Fabric]"
filename = "farmers-delight-fabric-1.18.1-0.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3559/302/farmers-delight-fabric-1.18.1-0.2.0.jar"
hash-format = "murmur2"
hash = "532056296"

[update]
[update.curseforge]
file-id = 3559302
project-id = 482834
release-channel = "beta"
