name = "Gilded Armor"
filename = "gildedarmor-1.3.1+fabric-1.17.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/8W2LklBN/versions/1.3.1/gildedarmor-1.3.1+fabric-1.17.1.jar"
hash-format = "sha512"
hash = "f2db6c55880d7680258e0d5a7de86f12fc0046b3f88e5df9fab7df4595aa950a141896588b8718998cc39b43c76eed4f29457dee008bee13bf44042aa0c9d1f8"

[update]
[update.modrinth]
mod-id = "8W2LklBN"
version = "avCgHPeb"
