name = "Immersive Portals"
filename = "immersive-portals-0.34-mc1.17.1-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3546/5/immersive-portals-0.34-mc1.17.1-fabric.jar"
hash-format = "murmur2"
hash = "1105806037"

[update]
[update.curseforge]
file-id = 3546005
project-id = 332273
release-channel = "beta"
