name = "Immersive Portals"
filename = "immersive-portals-1.1.7-mc1.18.1-fabric.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/zJpHMkdD/versions/1.1.7-1.18.1/immersive-portals-1.1.7-mc1.18.1-fabric.jar"
hash-format = "sha512"
hash = "66a0a5786c6be825822516205f35f587d33b3c17c5c3fa6ebe3a24ffceb630cca2f37c9883d802baea9b3c9784083c085e146949906ee519fa05c5c0d4a487b6"

[update]
[update.modrinth]
mod-id = "zJpHMkdD"
version = "1e2JzzZs"
