name = "Immersive Portals"
filename = "immersive-portals-1.0.4-mc1.18-fabric.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/zJpHMkdD/versions/1.0.4-1.18/immersive-portals-1.0.4-mc1.18-fabric.jar"
hash-format = "sha512"
hash = "ce08ed7998aac1227d7d2364652461992b36bd580670d42c570b51b249604aae8944f299e31d824c9b918b58df3cc23608158331becb74dfa4d1540bcd08b1c1"

[update]
[update.modrinth]
mod-id = "zJpHMkdD"
version = "U9Cb1VzA"
