name = "Immersive Portals"
filename = "immersive-portals-1.0.3-mc1.18-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3551/303/immersive-portals-1.0.3-mc1.18-fabric.jar"
hash-format = "murmur2"
hash = "568704856"

[update]
[update.curseforge]
file-id = 3551303
project-id = 332273
release-channel = "beta"
