name = "Inventory Totem (Fabric)"
filename = "inventorytotem-fabric_1.18.x-1.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/208/inventorytotem-fabric_1.18.x-1.5.jar"
hash-format = "murmur2"
hash = "1615190260"

[update]
[update.curseforge]
file-id = 3542208
project-id = 529954
release-channel = "beta"
