name = "Inventory Hotswap"
filename = "inventory-hotswap-fabric-1.18-1.3.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3549/75/inventory-hotswap-fabric-1.18-1.3.jar"
hash-format = "murmur2"
hash = "3201088213"

[update]
[update.curseforge]
file-id = 3549075
project-id = 423235
release-channel = "beta"

[option]
description = "Swap hotbar items with ones in the column above"
optional = true
default = true
