name = "InvMove (Fabric)"
filename = "InvMove-fabric-1.18-0.1.0.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/McNdqLv2/versions/1.18-0.1.0/InvMove-fabric-1.18-0.1.0.jar"
hash-format = "sha512"
hash = "9a7044b00191167bc070536317b000cb85389c9a26636586d24cd829a572f89231be521cf3a6dc016cdeb35ce206e2ef4f611df58e92b7e0885b05131db88863"

[update]
[update.modrinth]
mod-id = "McNdqLv2"
version = "njGdxwF4"

[option]
description = "Ability to walk around while in inventories"
optional = true
default = false
