name = "Iris Shaders"
filename = "iris-mc1.18-1.1.3.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/YL57xq9U/versions/mc1.18-1.1.3/iris-mc1.18-1.1.3.jar"
hash-format = "sha512"
hash = "6939ff2672e645873d01c9eb55b43f7a81ebcb864d0ce9127f7fc6b8df0f490ab54d990da83c8f68757eb94c623e606bda27bec16fc4be31c7418df8d3272b7e"

[update]
[update.modrinth]
mod-id = "YL57xq9U"
version = "Hw3w5BnI"

[option]
description = "A shaders mod, backward compatible with OptiFine shaders"
optional = true
default = false
