name = "Iris Shaders"
filename = "iris-mc1.17-1.1.3.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/YL57xq9U/versions/mc1.17.1-1.1.3/iris-mc1.17-1.1.3.jar"
hash-format = "sha512"
hash = "a28042758fc8b8ec71c197b3cf18e3e4558a5219df673074910204383757113ebfa39aefba38a0b84c04d501005d7ab5ccee36dd747c69e64799c8764fc2fa3d"

[update]
[update.modrinth]
mod-id = "YL57xq9U"
version = "RtuAfhnO"

[option]
optional = true
description = "A shaders mod, backward compatible with OptiFine shaders"
default = false
