name = "Iron Bundles"
filename = "ironbundles-1.0.2+1.17.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/GrvAgLaJ/versions/1.0.2+1.17/ironbundles-1.0.2+1.17.jar"
hash-format = "sha512"
hash = "e6160ad95345c32abe501aa9eba026f5651d5227b0533c68bb4675bf874c259b50aca60d07e9c26ce58c84950d097e03bde7c26dbc2c695aea2d78ff2ce93856"

[update]
[update.modrinth]
mod-id = "GrvAgLaJ"
version = "kJvxTAko"
