name = "Item Model Fix (Fabric)"
filename = "item-model-fix-1.0.2+1.17.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3344/195/item-model-fix-1.0.2+1.17.jar"
hash-format = "murmur2"
hash = "1083414010"

[update]
[update.curseforge]
file-id = 3344195
project-id = 399798
release-channel = "beta"
