name = "Item Model Fix (Fabric)"
filename = "item-model-fix-1.0.3+1.18.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3573/935/item-model-fix-1.0.3+1.18.jar"
hash-format = "murmur2"
hash = "1104738622"

[update]
[update.curseforge]
file-id = 3573935
project-id = 399798
release-channel = "beta"
