name = "Item Scroller"
filename = "itemscroller-fabric-1.18.0-0.15.0.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3544/231/itemscroller-fabric-1.18.0-0.15.0.jar"
hash-format = "murmur2"
hash = "4093658145"

[update]
[update.curseforge]
file-id = 3544231
project-id = 242064
release-channel = "beta"

[option]
description = "Adds several ways of moving items in inventory GUIs"
optional = true
default = false
