name = "Item Scroller"
filename = "itemscroller-fabric-1.17.1-0.15.0-dev.20210707.005506.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3379/264/itemscroller-fabric-1.17.1-0.15.0-dev.20210707.005506.jar"
hash-format = "murmur2"
hash = "2166710212"

[update]
[update.curseforge]
file-id = 3379264
project-id = 242064
release-channel = "beta"

[option]
description = "Adds several ways of moving items in inventory GUIs"
optional = true
default = false
