name = "Item Scroller"
filename = "itemscroller-fabric-1.17.1-0.15.0-dev.20211201.010054.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3542/814/itemscroller-fabric-1.17.1-0.15.0-dev.20211201.010054.jar"
hash-format = "murmur2"
hash = "3186127089"

[update]
[update.curseforge]
file-id = 3542814
project-id = 242064
release-channel = "beta"

[option]
optional = true
description = "Adds several ways of moving items in inventory GUIs"
