name = "Lithium"
filename = "lithium-fabric-mc1.17.1-0.7.5.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/gvQqBUqZ/versions/mc1.17.1-0.7.5/lithium-fabric-mc1.17.1-0.7.5.jar"
hash-format = "sha512"
hash = "8e8bf5ea7856773d48018b8a1fd3c34306794c79b914beda3466ac43daee53172f610fd39a62801834b4751d83a9b988ad1f3fc9c9bc2ad1787fba19626a684e"

[update]
[update.modrinth]
mod-id = "gvQqBUqZ"
version = "FHFKMKeu"
