name = "Modern Industrialization"
filename = "Modern-Industrialization-1.0.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/Gov5Dboq/versions/1.0.2/Modern-Industrialization-1.0.2.jar"
hash-format = "sha512"
hash = "9d2a3058111e0093cac32084605834bcf9b9e007e813014c3d79f2b6b018f10bd902d02440a1d9534c57ebd2314c4d54510979c33e014585d3f2693a1947fb3b"

[update]
[update.modrinth]
mod-id = "Gov5Dboq"
version = "1Gr8mg4d"
