name = "Mouse Wheelie (Fabric)"
filename = "mousewheelie-1.8.0+mc1.18-pre5.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3538/698/mousewheelie-1.8.0+mc1.18-pre5.jar"
hash-format = "murmur2"
hash = "1381384174"

[update]
[update.curseforge]
file-id = 3538698
project-id = 317514
release-channel = "beta"

[option]
description = "Features item scrolling, inventory sorting, item refilling and more"
optional = true
default = false
