name = "Mouse Wheelie"
filename = "mousewheelie-1.8.0+mc1.17.1.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/u5Ic2U1u/versions/1.8.0+mc1.17.1/mousewheelie-1.8.0+mc1.17.1.jar"
hash-format = "sha512"
hash = "2246661deea5d0c0528d5bfcb8a841dbabedc91a91007726994fd2b3a88fa5743b5e911acc21f0eca1da890ffe74209bfe1c21e6108f4c550ea2460f94ee4842"

[update]
[update.modrinth]
mod-id = "u5Ic2U1u"
version = "FOq96T8x"

[option]
description = "Features item scrolling, inventory sorting, item refilling and more"
optional = true
default = false
