name = "Not Enough Crashes"
filename = "notenoughcrashes-4.1.3+1.18.1-fabric.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/yM94ont6/versions/4.1.3+1.18.1-fabric/notenoughcrashes-4.1.3+1.18.1-fabric.jar"
hash-format = "sha512"
hash = "fb9db9d6e05a857c2aaced31d2f3b15b76a2adc8b56e1c207115851714a3aeda4566a5f4e4b283380a80d922e142573acc3f6c7264d9bc084de3922d0a7b44eb"

[update]
[update.modrinth]
mod-id = "yM94ont6"
version = "FNiqTGuz"
