name = "OverpoweredMending"
filename = "OverpoweredMending-1.18.1-2.3.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/DKzFWXbg/versions/1.18.1-2.3.1/OverpoweredMending-1.18.1-2.3.1.jar"
hash-format = "sha512"
hash = "d114ee5065e6389951ed2cea55526156cf9c653d6a3941158fab2a63b5ba947da9639d6b42e2062c4eb3112f665082b76f371bc9e2bc886f023de0c9ea25a28c"

[update]
[update.modrinth]
mod-id = "DKzFWXbg"
version = "1axij8rv"
