name = "Patchouli (Fabric)"
filename = "Patchouli-1.17.1-59-FABRIC.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3540/261/Patchouli-1.17.1-59-FABRIC.jar"
hash-format = "murmur2"
hash = "1637612341"

[update]
[update.curseforge]
file-id = 3540261
project-id = 393236
release-channel = "beta"
