name = "Pitch Dark"
filename = "pitch-dark-2.0.0-fabric.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/z81pxvlB/versions/2.0.0-fabric/pitch-dark-2.0.0-fabric.jar"
hash-format = "sha512"
hash = "952b3ff6c31c6e848c0e6ab8bb0837101b5475bc580e0aa42231d3695b56ec18e74e6b266860a0341261d4b5c8ed2df9578b8791683d8db65c4343cdfdc945ad"

[update]
[update.modrinth]
mod-id = "z81pxvlB"
version = "z6okGkaM"
