name = "Presence Footsteps"
filename = "PresenceFootsteps-r35-1.17.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/rcTfTZr3/versions/35/PresenceFootsteps-r35-1.17.jar"
hash-format = "sha512"
hash = "1c919f45266a8549d8c168fe90406635fb6f3746a51ebe5c06888258b06158317f32916d20027bd21718133202c3547a787aa070d08abeb064518fb9f592750c"

[update]
[update.modrinth]
mod-id = "rcTfTZr3"
version = "3R7j6E4Z"

[option]
optional = true
description = "New and improved dynamic sounds for every block the player walks on"
