name = "Quick Shulker"
filename = "quickshulker-1.3.1-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3543/268/quickshulker-1.3.1-1.18.jar"
hash-format = "murmur2"
hash = "2901753045"

[update]
[update.curseforge]
file-id = 3543268
project-id = 362669
release-channel = "beta"
