name = "Reroll"
filename = "reroll-1.4.0-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3575/83/reroll-1.4.0-1.18.1.jar"
hash-format = "murmur2"
hash = "1861730190"

[update]
[update.curseforge]
file-id = 3575083
project-id = 401753
release-channel = "beta"
