name = "Respawnable Pets"
filename = "respawnablepets-1.18-1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3541/956/respawnablepets-1.18-1.jar"
hash-format = "murmur2"
hash = "2877349360"

[update]
[update.curseforge]
file-id = 3541956
project-id = 319582
release-channel = "beta"
