name = "Roughly Enough Items Fabric (REI)"
filename = "RoughlyEnoughItems-7.0.343.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3545/879/RoughlyEnoughItems-7.0.343.jar"
hash-format = "murmur2"
hash = "3351030985"

[update]
[update.curseforge]
file-id = 3545879
project-id = 310111
release-channel = "beta"
