name = "Roughly Enough Items Fabric (REI)"
filename = "RoughlyEnoughItems-7.1.356.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3568/540/RoughlyEnoughItems-7.1.356.jar"
hash-format = "murmur2"
hash = "656153815"

[update]
[update.curseforge]
file-id = 3568540
project-id = 310111
release-channel = "beta"
