name = "ShulkerBoxTooltip"
filename = "shulkerboxtooltip-3.0.4+1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3531/114/shulkerboxtooltip-3.0.4+1.17.1.jar"
hash-format = "murmur2"
hash = "2626429364"

[update]
[update.curseforge]
file-id = 3531114
project-id = 315811
release-channel = "beta"
