name = "Simple Voice Chat"
filename = "voicechat-fabric-1.18-2.1.20.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3550/222/voicechat-fabric-1.18-2.1.20.jar"
hash-format = "murmur2"
hash = "297176058"

[update]
[update.curseforge]
file-id = 3550222
project-id = 416089
release-channel = "beta"
