name = "Simple Voice Chat"
filename = "voicechat-fabric-1.17.1-2.1.14.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3536/24/voicechat-fabric-1.17.1-2.1.14.jar"
hash-format = "murmur2"
hash = "3116293944"

[update]
[update.curseforge]
file-id = 3536024
project-id = 416089
release-channel = "beta"

[option]
description = "Adds a proximity voice chat to your Minecraft server"
optional = true
default = true
