name = "Simple Voice Chat"
filename = "voicechat-fabric-1.17.1-2.1.19.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3548/642/voicechat-fabric-1.17.1-2.1.19.jar"
hash-format = "murmur2"
hash = "3387207774"

[update]
[update.curseforge]
file-id = 3548642
project-id = 416089
release-channel = "beta"

[option]
optional = true
description = "Adds a proximity voice chat to your Minecraft server"
default = true
