name = "Sky Villages"
filename = "SkyVillages-1.0.1-1.17.1-fabric.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/mb68eIfx/versions/SkyVillages-1.0.1/SkyVillages-1.0.1-1.17.1-fabric.jar"
hash-format = "sha512"
hash = "5d0d37ad2e94a06936788ae8711df4fe7e032fc782adbdce7ffc16fb33ac55cfe9d7ae90a3bcd3ddfd632c2a4417d934b4cc9caa7f8bd3af5888f3c8084062e4"

[update]
[update.modrinth]
mod-id = "mb68eIfx"
version = "2YkmTxRZ"
