name = "Smooth Swapping"
filename = "Fabric-1.18-SmoothSwapping-0.4.3.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/ydZic5r4/versions/0.4.3/Fabric-1.18-SmoothSwapping-0.4.3.jar"
hash-format = "sha512"
hash = "63ae06a42ade86cf542c269e7bf225b7b9d698b3864314faf090fc4b579eb91e398b70b9b4d251e6d6e66dcbe45489cee50cd873b867a980c16494c02be95acb"

[update]
[update.modrinth]
mod-id = "ydZic5r4"
version = "ujbCytmY"

[option]
description = "Moves items smoothly in inventories"
optional = true
default = false
