name = "Sodium + Iris Shaders"
filename = "iris-and-sodium-mc1.17-1.1.2+build.9.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/YL57xq9U/versions/mc1.17.1-1.1.2/iris-and-sodium-mc1.17-1.1.2+build.9.jar"
hash-format = "sha512"
hash = "55a13a56c6eed76ab98fdce9bcf8f4dbaa66a2b09f6caf254fdd24ff4bd0f147542e380be9f854b85048848eaaa1d478beef84c3b8f4f271a345b529f312a161"

[update]
[update.modrinth]
mod-id = "YL57xq9U"
version = "YwBoFV6P"

[option]
description = "A shaders mod, backward compatible with OptiFine shaders"
optional = true
default = false
