name = "Status Effect Timer"
filename = "statuseffecttimer-1.0.3.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/T9FDHbY5/versions/1.0.3/statuseffecttimer-1.0.3.jar"
hash-format = "sha512"
hash = "e926653d3a1ffc598b8c49bf3c23209e534210c3f0ea5fce594a6613e97c0137cdb6b296d3aa44de76942700ea96e44138932ef44d6d7644e2d2308724258aa7"

[update]
[update.modrinth]
mod-id = "T9FDHbY5"
version = "Fldk6PQJ"
