name = "Stockpile"
filename = "stockpile-1.1.5+1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3476/863/stockpile-1.1.5+1.17.1.jar"
hash-format = "murmur2"
hash = "1011797764"

[update]
[update.curseforge]
file-id = 3476863
project-id = 299913
release-channel = "beta"
