name = "Stoneholm"
filename = "stoneholm-1.3.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/zQoJfY3W/versions/1.3/stoneholm-1.3.jar"
hash-format = "sha512"
hash = "7062900df388ef8b89c2ee543ffe68cc406143fe6076a06655c058cd369ae1b3f4b5278e286b1a7d9ddb48d2fed8b89d693a6300fe8672e2f7bccb49d500c2ad"

[update]
[update.modrinth]
mod-id = "zQoJfY3W"
version = "UneaOKZ2"
