name = "Xaero's Minimap"
filename = "Xaeros_Minimap_21.22.6_Fabric_1.18.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3574/63/Xaeros_Minimap_21.22.6_Fabric_1.18.jar"
hash-format = "murmur2"
hash = "1380848437"

[update]
[update.curseforge]
file-id = 3574063
project-id = 263420
release-channel = "beta"

[option]
optional = true
description = "Minimap which keeps the aesthetic of Vanilla"
