name = "Xaero's World Map"
filename = "XaerosWorldMap_1.18.9_Fabric_1.18.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3576/612/XaerosWorldMap_1.18.9_Fabric_1.18.jar"
hash-format = "murmur2"
hash = "3463406173"

[update]
[update.curseforge]
file-id = 3576612
project-id = 317780
release-channel = "beta"

[option]
optional = true
description = "Self-writing fullscreen map"
