name = "Xaero's Minimap"
filename = "Xaeros_Minimap_21.22.3.1_Fabric_1.18.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3551/764/Xaeros_Minimap_21.22.3.1_Fabric_1.18.jar"
hash-format = "murmur2"
hash = "75692968"

[update]
[update.curseforge]
file-id = 3551764
project-id = 263420
release-channel = "beta"

[option]
description = "Minimap which keeps the aesthetic of Vanilla"
optional = true
default = false
